/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Allan
 */
public class FiveCardDrawTableGUI extends javax.swing.JFrame
{
    int counter;
    FiveCardDrawPlayerGUI player1Bord;
    FiveCardDrawPlayerGUI player2Bord;
    FiveCardDrawPlayerGUI player3Bord;
    FiveCardDrawPlayerGUI player4Bord;
    /**
     * Creates new form FiveCardDrawTableGUI
     */
    public FiveCardDrawTableGUI()
    {
        initComponents();
        counter = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton2 = new javax.swing.JButton();
        player1Panel = new javax.swing.JPanel();
        player1Name = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblIsDealer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNewPlayer = new javax.swing.JButton();
        player2Panel = new javax.swing.JPanel();
        player2Name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        player4Panel = new javax.swing.JPanel();
        player4Name = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        player3Panel = new javax.swing.JPanel();
        player3Name = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblPulje = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 200));
        setPreferredSize(new java.awt.Dimension(300, 200));
        getContentPane().setLayout(null);

        player1Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        player1Panel.setLayout(null);

        player1Name.setText("Player 1");
        player1Panel.add(player1Name);
        player1Name.setBounds(60, 0, 50, 14);

        jLabel8.setText("Indsats:");
        player1Panel.add(jLabel8);
        jLabel8.setBounds(20, 20, 50, 14);

        lblIsDealer.setText("Dealer!");
        player1Panel.add(lblIsDealer);
        lblIsDealer.setBounds(40, 40, 40, 14);

        jLabel4.setText("0000");
        player1Panel.add(jLabel4);
        jLabel4.setBounds(70, 20, 30, 14);

        getContentPane().add(player1Panel);
        player1Panel.setBounds(190, 0, 110, 74);

        jPanel2.setLayout(null);

        btnNewPlayer.setText("Tilføj ny spiller");
        btnNewPlayer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNewPlayerActionPerformed(evt);
            }
        });
        jPanel2.add(btnNewPlayer);
        btnNewPlayer.setBounds(90, 10, 120, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 160, 300, 41);

        player2Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        player2Panel.setLayout(null);

        player2Name.setText("Player 2");
        player2Panel.add(player2Name);
        player2Name.setBounds(60, 0, 50, 14);

        jLabel7.setText("Indsats:");
        player2Panel.add(jLabel7);
        jLabel7.setBounds(20, 20, 50, 14);

        jLabel6.setText("0000");
        player2Panel.add(jLabel6);
        jLabel6.setBounds(70, 20, 30, 14);

        getContentPane().add(player2Panel);
        player2Panel.setBounds(190, 80, 110, 74);

        player4Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        player4Panel.setLayout(null);

        player4Name.setText("Player 4");
        player4Panel.add(player4Name);
        player4Name.setBounds(0, 0, 50, 14);

        jLabel9.setText("Indsats:");
        player4Panel.add(jLabel9);
        jLabel9.setBounds(10, 20, 50, 14);

        jLabel12.setText("0000");
        player4Panel.add(jLabel12);
        jLabel12.setBounds(60, 20, 30, 14);

        getContentPane().add(player4Panel);
        player4Panel.setBounds(0, 0, 110, 74);

        player3Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        player3Panel.setLayout(null);

        player3Name.setText("Player 3");
        player3Panel.add(player3Name);
        player3Name.setBounds(0, 0, 50, 14);

        jLabel11.setText("Indsats:");
        player3Panel.add(jLabel11);
        jLabel11.setBounds(10, 20, 50, 14);

        jLabel13.setText("0000");
        player3Panel.add(jLabel13);
        jLabel13.setBounds(60, 20, 30, 14);

        getContentPane().add(player3Panel);
        player3Panel.setBounds(0, 80, 110, 74);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel5.setText("Puljen:");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(20, 50, 40, 14);

        lblPulje.setText("0000");
        jPanel6.add(lblPulje);
        lblPulje.setBounds(30, 70, 30, 14);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(110, 0, 80, 154);

        jPanel7.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel7.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 300, 170);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(0, 210, 300, 170);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-316)/2, (screenSize.height-423)/2, 316, 423);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewPlayerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNewPlayerActionPerformed
    {//GEN-HEADEREND:event_btnNewPlayerActionPerformed
        //System.out.println("tester lige knappen på bordet! " );
        
        if(counter < 5 )
        {
            //System.out.println("Tilføjer spiller " + counter );
            
            if(counter == 1)
            {
                player1Bord = new FiveCardDrawPlayerGUI();
                player1Bord.setBounds(850, 50, 424, 246);
                player1Bord.setVisible(true);
                player1Bord.setLabelsPlayer("Player 1", " - ", "200", "0");
            }
            else if(counter == 2)
            {
                player2Bord = new FiveCardDrawPlayerGUI();
                player2Bord.setBounds(850, 350, 424, 246);
                player2Bord.setVisible(true);
                player2Bord.setLabelsPlayer("Player 2", " - ", "200", "0");
            }
            else if(counter == 3)
            {
                player3Bord = new FiveCardDrawPlayerGUI();
                player3Bord.setBounds(90, 350, 424, 246);
                player3Bord.setVisible(true);
                player3Bord.setLabelsPlayer("Player 3", " - ", "200", "0");
            }
            else if(counter == 4)
            {
                player4Bord = new FiveCardDrawPlayerGUI();
                player4Bord.setBounds(90, 50, 424, 246);
                player4Bord.setVisible(true);
                player4Bord.setLabelsPlayer("Player 4", " - ", "200", "0");
                btnNewPlayer.setEnabled(false);
            }
            else
            {
                System.out.println("Der er sket en fejl da der blev tilføjet spillere!");
            }
            
            counter = counter + 1;
        }
        else
        {
            //System.out.println("ikke flere spillere!");
            btnNewPlayer.setEnabled(false);
        }
    }//GEN-LAST:event_btnNewPlayerActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[])
//    {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try
//        {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//            {
//                if ("Nimbus".equals(info.getName()))
//                {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        }
//        catch (ClassNotFoundException ex)
//        {
//            java.util.logging.Logger.getLogger(FiveCardDrawTableGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        catch (InstantiationException ex)
//        {
//            java.util.logging.Logger.getLogger(FiveCardDrawTableGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        catch (IllegalAccessException ex)
//        {
//            java.util.logging.Logger.getLogger(FiveCardDrawTableGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        catch (javax.swing.UnsupportedLookAndFeelException ex)
//        {
//            java.util.logging.Logger.getLogger(FiveCardDrawTableGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable()
//        {
//            public void run()
//            {
//                new FiveCardDrawTableGUI().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewPlayer;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblIsDealer;
    private javax.swing.JLabel lblPulje;
    private javax.swing.JLabel player1Name;
    private javax.swing.JPanel player1Panel;
    private javax.swing.JLabel player2Name;
    private javax.swing.JPanel player2Panel;
    private javax.swing.JLabel player3Name;
    private javax.swing.JPanel player3Panel;
    private javax.swing.JLabel player4Name;
    private javax.swing.JPanel player4Panel;
    // End of variables declaration//GEN-END:variables
}
